### ISSUE TITLE
Feature request : Translate

### ISSUE THREAD

**Issue by JCC66** [landgraf-dev/aws-sdk-delphi#1]
Looks great!
I thought adding new services would be simple, but looking at the packages that are available it is quite an intimidating amount of code. Would love to add translation.. 
https://aws.amazon.com/translate/
Thx!

**Comment by wlandgraf** [comment]
AWS Translate is now added to the SDK. There is also a sample available in https://github.com/landgraf-dev/aws-sdk-delphi-samples.
