### ISSUE TITLE
Unable to install packages. 

### ISSUE THREAD

**Issue by LeifEirik** [landgraf-dev/aws-sdk-delphi#10]
Hi,

I'm revisting this library as I now have a bussiness use case. Unfortunately I'm unable to install it for my Delphi 11.3 (Patch 1).
After dowloading and then openeing the "AWSPackages.groupproj", and doing a Build All on the awscore280.bpl, I get an error in the AWS:Region.rc. The error is: **[BRCC32 Error] AWS.Region.rc(1): Error Could not open input file C:Async;C:\DComp\TMS\TMS.RC** 
My attention was automatcally drawn to the _"C:Async"_ part of the error message, where there are no "\\". 

Not sure if there is any dependencies to TMS libraries, but I do have all TMS Biz installed on my system.

Any hints or tips on how to resolve this greatly appricated.

**Comment by wlandgraf** [comment]
Hi @LeifEirik,

AWS doesn't require any TMS library or any other 3rd party library (free or paid). It should work and compile with a vanilla Delphi installation.

About the error you are getting, it's for now a mystery to me. But I have just added a `.gitattributes` file to the repository that, first, should address issues with CRLF/LF which might happen depending on the Git client configuration. Please delete the repo locally and clone it again.

If this doesn't solve the issue, then the reference to TMS might be related to some misconfiguration in your Delphi library path. Do you have strange paths in your library path? Is it possible to post your Delphi library path here so we can inspect and see if there is something wrong with it?

**Comment by LeifEirik** [comment]
Hi @wlandgraf ,

I deleted my repo copy and cloned it again. This time I did not see any "lineending" messages. But I still see the same error as before when Building the packages. I have looked at my library path, but I do not see anything suspicious to be honest.

Here's a overview:
  
![D11_LibPath](https://github.com/landgraf-dev/aws-sdk-delphi/assets/45846689/57329463-164e-48ae-b66d-a2feb1570eef)

When doing a Build of awscore280.bpl, the error I get is still **[BRCC32 Error] AWS.Region.rc(1): Error Could not open input file C:Async;C:\DComp\TMS\TMS.RC**

I see thata a file called **TMS.RC** is mentioned. 

And the message in Delphi is:

> brcc32 command line for "..\..\Resources\AWS.Region.rc"
  c:\program files (x86)\embarcadero\studio\22.0\bin\brcc32.exe -dDEBUG -i"c:\program files (x86)\embarcadero\studio\22.0\lib\Win32\debug";
  "C:\DComp\TMS\TMS Scripter\packages\d11\.\Win32\Debug";"C:\DComp\TMS\TMS BIZ Core Library\packages\d11\.\Win32\Debug";"C:\DComp\TMS\TMS 
  Aurelius\packages\d11\.\Win32\Debug";"C:\DComp\TMS\TMS Sparkle\packages\d11\.\Win32\Debug";"C:\DComp\TMS\TMS XData\packages\d11\.\Win32\Debug";
  "C:\DComp\TMS\TMS Sphinx\packages\d11\.\Win32\Debug";"C:\DComp\TMS\TMS Echo\packages\d11\.\Win32\Debug";"C:\DComp\TMS\TMS 
  Logging\packages\d11\.\Win32\Debug";"C:\DComp\TMS\TMS RemoteDB\packages\d11\.\Win32\Debug";"c:\program files 
  (x86)\embarcadero\studio\22.0\lib\Win32\release";C:\Users\leo\Documents\Embarcadero\Studio\22.0\Imports;
  C:\Users\leo\Documents\Embarcadero\Studio\22.0\Imports\Win32;"c:\program files (x86)\embarcadero\studio\22.0\Imports";
  C:\Users\Public\Documents\Embarcadero\Studio\22.0\Dcp;"c:\program files (x86)\embarcadero\studio\22.0\include";C:\DComp\NEON\Source;"C:\DComp\TMS\TMS 
  WEB Core RSXE14";"C:\DComp\TMS\TMS WEB Core RSXE14\Win32";"C:\DComp\TMS\TMS WEB Core RSXE14\Component Library Source";"Z:\Work\TDWOS Components\TDW 
  Pack Pro";"C:\DComp\TMS\TMS FNC Core";"C:\DComp\TMS\TMS FNC Core\Delphi11\Win32\Release";"C:\Program Files (x86)\DevExpress\VCL\Library\RS28\\";
  "C:\DComp\TMS\TMS Async";"C:\DComp\TMS\TMS Async\Delphi11\Win32\Release";"C:\DComp\TMS\TMS VCL UI Pack";"C:\DComp\TMS\TMS VCL UI 
  Pack\Delphi11\Win32\Release";"C:\DComp\TMS\TMS VCL UI Pack\xlsAdapter";"C:\DComp\TMS\TMS Scripter\packages\d11\.\Win32\Release";"C:\DComp\TMS\TMS 
  Scripter\source\imports\extra";"C:\DComp\TMS\TMS MQTT";"C:\DComp\TMS\TMS MQTT\Delphi11\Win32\Release";"C:\DComp\TMS\TMS BIZ Core 
  Library\packages\d11\.\Win32\Release";"C:\DComp\TMS\TMS BIZ Core Library\source\extra";"C:\DComp\TMS\TMS Aurelius\packages\d11\.\Win32\Release";
  "C:\DComp\TMS\TMS Aurelius\source\drivers";"C:\DComp\TMS\TMS Sparkle\packages\d11\.\Win32\Release";"C:\DComp\TMS\TMS Sparkle\source\extra";
  "C:\DComp\TMS\TMS Sparkle\source\app";"C:\DComp\TMS\TMS XData\packages\d11\.\Win32\Release";"C:\DComp\TMS\TMS Sphinx\packages\d11\.\Win32\Release";
  "C:\DComp\TMS\TMS Echo\packages\d11\.\Win32\Release";"C:\DComp\TMS\TMS Logging\packages\d11\.\Win32\Release";"C:\DComp\TMS\TMS Logging\source\extra";
  "C:\DComp\TMS\TMS RemoteDB\packages\d11\.\Win32\Release";"C:\DComp\TMS\TMS RemoteDB\source\drivers";C:\DComp\APPERCEPT\Source;
  C:\DComp\APPERCEPT\Source\AWS;C:\DComp\APPERCEPT\Source\Components ..\..\Resources\AWS.Region.rc -fo.\Win32\Debug\AWS.Region.res 
[BRCC32 Error] AWS.Region.rc(1): Error Could not open input file Z:Async;C:\DComp\TMS\TMS.RC

**Comment by LeifEirik** [comment]
Hi @wlandgraf,

Wow, just after posting my last message here, I realized an issue with my Library Path. 
The issues was that I for some unknown reason had this entry:
`$(DXVCL)\Library\RS28\\`

Please notice the two backspaces. After removing the addtional backspace your SDK compiled just fine.
So it turned out it had noithing to do with this SDK. Very sorry for any confusion I may have caused you :)
