### ISSUE TITLE
The awss3280.bpl will not build

### ISSUE THREAD

**Issue by LeifEirik** [landgraf-dev/aws-sdk-delphi#12]
In Delphi 11.3 Patch 1:
1. I've cloned your latest available AWS SDK to "C:\DComp\WAGNER\".
2. I've added: **C:\DComp\WAGNER\Packages\d11\Win32\Release** to the Delphi library path
3. Opened AWSPackages.groupproj and build each package in **Release** mode.
4. All packages build just fine except the **awss3280.bpl**, this one gives me the error:
**[dcc32 Error] AWS.S3.Pipeline.PostMarshallHandler.pas(32): E2003 Undeclared identifier: 'THashSet<>'**
In file: AWS.S3.Pipeline.PostMarshallHandler, at line #32

Anything I'm missing or overlooking here?

**Comment by wlandgraf** [comment]
Commit fddc51c should fix this. Can you please confirm.

**Comment by LeifEirik** [comment]
I can confirm that the fix resolved the issue.
Thank you.
