### ISSUE TITLE
Undeclared identifier: 'IAmazonSQS' in example.

### ISSUE THREAD

**Issue by LeifEirik** [landgraf-dev/aws-sdk-delphi#13]
Hi,

After sccsessfully building all packages (except awss3280.bpl), I started a new win 32 vcl application.
Added AWS.SQS to my uses clause, and tried to use the **WriteMessageIds** procedure from the README.md like this:

![AWSSDK_003](https://github.com/landgraf-dev/aws-sdk-delphi/assets/45846689/028d5102-f553-448f-9e8e-e8bf5ee4cb4c)

As indicated by the attach code capture, Delphi does not seem to be able to identify/locate any of the following variable types:

> var
  Client: IAmazonSQS;
  Response: IReceiveMessageResponse;
  Request: IReceiveMessageRequest;
  Msg: AWS.SQS.TMessage;

Any hint og suggestion on what I'm missing or doing wromg here?

**Comment by wlandgraf** [comment]
Is the error only while editing, i.e. are you able to compile the application, or you also get an error when compiling it?

Do you have other AWS SDK installed in your Delphi IDE? Maybe it's trying to use a different `AWS.SQS` file.

**Comment by LeifEirik** [comment]
Yes I had another AWS SDK installed. After removing those references, my issue was resolved.
Thank you!
