### ISSUE TITLE
Does it rely on AWS SDK for .NET?

### ISSUE THREAD

**Issue by edwinyzh** [landgraf-dev/aws-sdk-delphi#5]
Hi,

Is this lib pure pascal or a wrapper of "[AWS SDK for .NET](https://github.com/aws/aws-sdk-net)"?

What's the oldest Delphi compiler supported?

Thanks.

**Comment by wlandgraf** [comment]
It's pure Pascal. We have only tested it on Delphi 10.4 Sydney and Delphi 11 Alexandria, but it might work in older Delphi versions. Not older than XE2, for sure.

**Comment by EverestSoftwareLLC** [comment]
Since posting 28 days ago, has anyone tested on Delphi 10.2?

**Comment by omonien** [comment]
Why don’t you test it and report your findings here?

--
Grüße / Regards,
Olaf Monien

Sent via iPhone

**Comment by EverestSoftwareLLC** [comment]
>Why don’t you test it and report your findings here?

I would need to purchase or use the trial version and install TMS Business Suite.  Not something I want to do for a test.

**Comment by wlandgraf** [comment]
@EverestSoftwareLLC The trial version is free, fully functional and harmless. You can install it, do the tests you need with AWS SDK for Delphi, and then uninstall it if you want to.

**Comment by EverestSoftwareLLC** [comment]
I will go a different route.
