### ISSUE TITLE
Exception ES3InvalidArgument with message 'The continuation token provided is incorrect'

### ISSUE THREAD

**Issue by joydeep-das5** [landgraf-dev/aws-sdk-delphi#7]
Hi,

I am trying to get a list of folders from a s3 bucket. The bucket contains more than 2K folders. When I am trying to use "NextContinuationToken", it gives the above error. Can you please help?

PS: I have tried the code from https://github.com/appercept/aws-sdk-delphi-samples/tree/main/S3Explorer and that also gives me the same error.

Thanks

**Comment by wlandgraf** [comment]
Can you please provide the exact code you are using?

**Comment by joydeep-das5** [comment]
Hi, 
I have created the following console application and tried to reproduce the error by specifying "MaxKeys" = 2. I don't actually need thousands of items in the bucket. The issue can be reproduced if there are more than 2 items in the bucket. Hope this will help to fix the issue.

`program S3Viewer;

{$APPTYPE CONSOLE}

{$R *.res}

uses
  System.SysUtils,
  Classes,
  AWS.S3;


function GetFirstBucket: IS3Bucket;
var
  S3Client: IS3Client;
  i : Integer;
begin
  S3Client := TS3Client.Create();

  var Response := S3Client.ListBuckets;

  for var Bucket in Response.Buckets do
  begin
    Result := Bucket;
    Break;
  end;
end;


var
  v2Request : IS3ListObjectsV2Request;
  v2Response : IS3ListObjectsV2Response;
  S3Client: IS3Client;
  I : Integer;
  S3Bucket : IS3Bucket;
  Options : IS3Options;
  BucketName, s : String;
begin
  Options := TS3Options.Create;
  try
    S3Bucket := GetFirstBucket;

    Options.Region := S3Bucket.Location;
    S3Client := TS3Client.Create( Options);

    v2Request := TS3ListObjectsV2Request.Create( S3Bucket.Name);
    v2Request.Bucket := S3Bucket.Name;
    v2Request.MaxKeys := 2;

    repeat
      v2Response := S3Client.ListObjectsV2( v2Request);
      for var Content in v2Response.Contents do
      begin
        Writeln( Content.Key);
      end;

      v2Request.ContinuationToken := v2Response.NextContinuationToken;
    until ( not v2Response.IsTruncated);
    Readln( s);
  except
    on E: Exception do
      Writeln(E.ClassName, ': ', E.Message);
  end;
end.
`

The fils is also attached herewith.
[S3 Viewer.zip](https://github.com/landgraf-dev/aws-sdk-delphi/files/13898010/S3.Viewer.zip)


![image](https://github.com/landgraf-dev/aws-sdk-delphi/assets/151124591/44dd227f-61a7-46ff-93d0-9b42bda94c2a)


Thanks !

**Comment by joydeep-das5** [comment]
Sorry ! my bad..
Will give it a try with your SDK.
Thanks !
